### ISSUE TITLE
更新了开发者工具直接报错

### ISSUE THREAD

**Issue by Young1993** [herculesJS/herculex#14]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
system.src.js:79 Uncaught (in promise) Error: Fetch error: 500 Internal Server Error
  Instantiating http://127.0.0.1:57779/node_modules/herculex/dist/index.js
  Loading http://127.0.0.1:57779/module/cardManage/useHelp-item/index.js?appxworker=1
  Loading /.tea/new-entryFiles-development/index.worker.js?t=222222
    at system.src.js:1512
LoaderError__Check_error_message_for_loader_stack @ system.src.js:79
(anonymous) @ system.src.js:289
Promise.then (async)
SystemJSLoader.import @ system.src.js:3967
(anonymous) @ index.worker.html?mockType=alipay&referrerInfo={"appId"%3A"2018051560091226"%2C"data"%3A{}}&query=:14
构建错误:
{ Error: Cannot find module 'babel-runtime/core-js/object/assign' from '/Users/wuyangjun/Downloads/tongka/mini_app_ali/busTemplate/node_modules/herculex/dist'
    at Function.module.exports [as sync] (/Applications/小程序开发者工具.app/Contents/Resources/app/extensions/volans-ide-tiny-project.asar/node_modules/resolve/lib/sync.js:58:15)
    at Object.resolvePath (/Applications/小程序开发者工具.app/Contents/Resources/app/extensions/volans-ide-tiny-project.asar/node_modules/@alipay/gravity-appx/src/workerpool/babelWorker.js:69:46)
    at mapPathString (/Applications/小程序开发者工具.app/Contents/Resources/app/extensions/volans-ide-tiny-project.asar/node_modules/babel-plugin-module-resolver/lib/utils.js:90:41)
    at PluginPass.transformCall (/Applications/小程序开发者工具.app/Contents/Resources/app/extensions/volans-ide-tiny-project.asar/node_modules/babel-plugin-module-resolver/lib/transformers/call.js:20:30)
    at NodePath._call (/Applications/小程序开发者工具.app/Contents/Resources/app/extensions/volans-ide-tiny-project.asar/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Applications/小程序开发者工具.app/Contents/Resources/app/extensions/volans-ide-tiny-project.asar/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Applications/小程序开发者工具.app/Contents/Resources/app/extensions/volans-ide-tiny-project.asar/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Applications/小程序开发者工具.app/Contents/Resources/app/extensions/volans-ide-tiny-project.asar/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Applications/小程序开发者工具.app/Contents/Resources/app/extensions/volans-ide-tiny-project.asar/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Applications/小程序开发者工具.app/Contents/Resources/app/extensions/volans-ide-tiny-project.asar/node_modules/@babel/traverse/lib/context.js:146:19) code: 'MODULE_NOT_FOUND' }

**Comment by blizzardzheng** [comment]
问一下 IDE 和 herculex 的版本

**Comment by Young1993** [comment]
ide 0.25.1 
herculex 0.1.6

**Comment by blizzardzheng** [comment]
@Young1993 更新一下版本到0.2.12把，向下兼容的
